### ISSUE TITLE
Need help for Synchronous Acquisition and Frame Transmission Delay

### ISSUE THREAD

**Issue by MaguetteSow** [alliedvision/VimbaPython#107]
Hello,
I want to know if the camera is in acquisition or not. But, in [camera.py](https://github.com/alliedvision/VimbaPython/blob/master/vimba/camera.py), there is only the `is_streaming()` function which returns `False` because I am not using asynchronous acquisition. 

This is how I acquire frames: 

```
            with Vimba.get_instance() as vimba :
                with vimba.get_camera_by_id(self.IpAddress) as cam:
                    while self.runningGrab:
                        try:
                            if self.attr_Mono8_read: 
                                frame8 = cam.get_frame()
                                print("Conv pixel 8:", frame8.convert_pixel_format(PixelFormat.Mono8))
                                # "replaces the original vimba.Frame object with a numpy.ndarray"
                                self.buff8 = frame8.as_numpy_ndarray()
                        except Exception as e:
                            print('-------> Grabbing error from the camera error  :', e) 
```

Is there a way to know if the camera is grabbing regardless of the type of acquisition ?

I am also looking for the equivalent features to Inter Packet delay and Frame Transmission Delay (from Basler). Maybe, `wait_for_frames()` ?
PS: I use Prosilica GT1290.
Thanks.

**Comment by arunprakash-avt** [comment]
Thank you fro the question. For this we have a feature called AcquisitionStatus. This feature returns Boolean value.

**Comment by MaguetteSow** [comment]
Thank you very much.

**Comment by MaguetteSow** [comment]
Thank you very much.
And what is the equivalent of Inter Packet Delay & Frame Transmission Delay?

**Comment by nordeh** [comment]
Hi,
that's true, Prosilica GT1290 doesn't support the AcquisitionStatus feature.

And instead of Inter Packet Delay & Frame Transmission Delay we suggest to control the bandwidth with the StreamBytesPerSecond feature value.

Thanks,
Norman
