### ISSUE TITLE
Short exposure times - timeout error

### ISSUE THREAD

**Issue by david-b36** [alliedvision/VimbaPython#109]
Hi,

I am using an Allied Vision Manta G-1620C camera with Vimba Python

Tryiing to use exposure times of below 750x10-6 s via cam.ExposureTimeAbs.set() causes a timeout error. More specifically:

vimba.error.VimbaTimeout: Frame capturing on Camera 'DEV_000F314F2D30' timed out

Is this is a VimbaPython issue?

Thank you

**Comment by arunprakash-avt** [comment]
With respect to the above issue , I  would like to know which camera you are using? I will also like to know which acquisition technique you are using?

**Comment by david-b36** [comment]
Hi,

The acquisition technique is based on the example from page 4 of the VimbaPython manual, ie:

import cv2
from vimba import *

with Vimba.get_instance() as vimba:
   cams = vimba.get_all_cameras()
   with cams[0] as cam:
      cam.ExposureTimeAbs.set(30000)
      frame = cam.get_frame()
      frame.convert_pixel_format(PixelFormat.Mono8)
      cv2.imwrite('frame.jpg', frame.as_opencv_image())

**Comment by arunprakash-avt** [comment]
The get_frame is a synchronous grab method. Which comes with a default Timeout. This value should be increased if the camera exposuretime or readtime is higher. This can be set as follows
frame = cam.get_frame(timeout_ms=3000) # default timeout_ms=2000

**Comment by david-b36** [comment]
Thank you
