### ISSUE TITLE
Cameras found: 0 

### ISSUE THREAD

**Issue by david-b36** [alliedvision/VimbaPython#112]
I'm trying to control an Allied Vision Manta G-1620C camera with VimbaPython/Ubuntu 20.04. 

After downloading VimbaPython and running the Python and GigE install .sh files, the script list_cameras.py returns Cameras found: 0 despite me being able to ping the camera IP address from the terminal.

I have checked, but is there another step necessary for VimbaPython to be able to recognise the camera?

Thank you

**Comment by nordeh** [comment]
Hi,
please login again to finally load the GenICam path variable and find the GigETL. Can you see the Manta in VimbaViewer?

Thanks
Norman

**Comment by arunprakash-avt** [comment]
Hi,
Please check if the GigE TL is installed properly using command "env". The GenICam path variable will be set for 32 bit and 64 bit. If you dont find please restart the PC after the GigETL installation.
Please refer to the document "Installing Vimba under Linux" for using vimba with Linux operating system in the below link.
https://www.alliedvision.com/de/support/faqs-application-notes/
Thanks
Arun Prakash

**Comment by david-b36** [comment]
Hi, I restarted my PC and check the GenICam path variable. I've not yet built Vimba Viewer. I also re downloaded the whole package and tried to install again. However I now receive the error:

vimba.error.VimbaSystemError: Failed to load library '(1)/Vimba_6_0/VimbaC/DynamicLib/x86_64bit/libVimbaC.so'. Please verify Vimba installation.

Could you advise on that?

Thank you

**Comment by arunprakash-avt** [comment]
Hi,
With respect to this issue. For further support I request you to send a email to support@alliedvision.com.
Thanks
Arun Prakash

**Comment by david-b36** [comment]
Hi, no problem, thank you

**Comment by arunprakash-avt** [comment]
Hi, 
I would like to know if your issue is solved and do you need further support for solving the above issue?

Thanks
Arun Prakash

**Comment by david-b36** [comment]
Hi, the issue is not solved but I will email support@alliedvision.com

Many thanks

**Comment by jmtatsch** [comment]
Just leaving this here as it might help someone:

On my ubuntu system I found the ufw firewall in its default configuration recently started to block the discovery packages of the camera. (You can find the blocked events in dmesg)
After whitelisting the camera in ufw I was able to find and work with the cameras as always.
