### ISSUE TITLE
Can't set AcquisitionFrameRateEnable

### ISSUE THREAD

**Issue by ian-wispr** [alliedvision/VimbaPython#121]
Hi. 

I recently received a new 1800 U-508c.  I have others cameras of the exact same model that do not have this issue.

The issue is in trying to set AcquisitionFrameRateEnable and TriggerMode from Python.  From using the Vimba GUI, I see that in order to set the TriggerMode to 'On', AcquisitionFrameRateEnable must be 'false'. And, to toggle AcquisitionFrameRateEnable, TriggerMode must be 'Off'.  (seems unnecessarily constraining, but fine).  However, I cannot set AcquisitionFrameRateEnable to False within the API, even when TriggerMode is 'Off'.  It simply stays True in spite of my command.  In turn, I'm unable to set TriggerMode to "On" from Python (the main goal) whenever AcquisitionFrameRateEnable is True.

To be clear, I do not encounter this issue from the Vimba GUI.  I'm able to change AcquisitionFrameRateEnable to False when TriggerMode is Off, and then set TriggerMode to On.  

I have updated the camera's firmware and Vimba software.

Prior to these commands, I do TriggerSelector.set('FrameStart'), and DeviceLinkThroughputLimit.set(Max).

**Comment by ian-wispr** [comment]
AcquisitionFrameRateEnable required an actual Python boolean, e.g. True, not a string.  No error is thrown in the latter case.

**Comment by Teresa-AlliedVision** [comment]
Hello Ian,
glad to hear you were able to resolve the issue. For further development and accessing features, have a look at the Alvium Features Reference that is available for download on the Allied Vision website. It has detailed information on the features and if they are int, float, boolean, string or enum features.
https://www.alliedvision.com/en/support/technical-documentation/alvium-usb-documentation/
Cheers,
Teresa
