### ISSUE TITLE
UART Alvium Usb-3 cameras -> setting timestamp

### ISSUE THREAD

**Issue by dagata-mining** [alliedvision/VimbaPython#128]
While scrolling through documentation and looking at the API, I've come to notice some recent change in USB camera documentations. https://cdn.alliedvision.com/fileadmin/content/documents/products/cameras/Alvium_USB/techman/Alvium-USB-Cameras_User-Guide.pdf

One that got my attention was the I/Os and UART. I was wondering if it would be possible to set the time on the usb cameras using a I/O UART  line? And from that I could get the real time of my images?

**Comment by BernardoLuck** [comment]
Hello! 
the I/O UART lines do not provide this functionality. The I/O UART lines can be used to control an external element that uses the serial communication. In other words, the camera is in charge of passing the serial data between Host-PC and the external device. However, the camera functionalities cannot be control from the I/Os. 
You can use the API to get the timestamp of the camera.

**Comment by dagata-mining** [comment]
Thanks for the answer,
So that means the internal camera time can only be set via usb and not UART?

**Comment by BernardoLuck** [comment]
yes, the communication to control the camera and access to its features happens via the USB Vision Protocol.

**Comment by dagata-mining** [comment]
> yes, the communication to control the camera and access to its features happens via the USB Vision Protocol.

Thanks
