### ISSUE TITLE
need to reconect to the camera evry time

### ISSUE THREAD

**Issue by shaizae10** [alliedvision/VimbaPython#144]
hi thare 
there is example of my code:

import numpy as np
from matplotlib import pyplot as plt

from HW.vimba import Vimba

```
class Sensor:
    def __init__(self, exptier_time: float = 0.3):
        self.frame = None
        vimba = Vimba()
        with vimba.get_instance() as vimba:
            self.camera = vimba.get_all_cameras()
            if len(self.camera) == 1:
                self.camera = self.camera[0]
                with self.camera as cam:
                    self.features = cam.get_all_features()[0]
            elif len(self.camera) == 0:
                raise IOError("camera didn't detected")
            else:
                pass # todo: crate GUI to ask user whitch camera
            print()

    def initialize_communication(self):
        pass

    def take_single_measurement(self) -> np.ndarray:

        self.frame = self.camera.get_frame()

        # frame.
        return self.frame


if __name__ == "__main__":
    exampel = Alvium1800()
    frame = exampel.take_single_measurement()
    plt.imshow(frame)
    plt.show()
```

evry time it is show me the next error 
RuntimeError: Called 'Camera.get_frame()' outside of 'with' - statement scope.
there is any wey that i can take frame any time whit out the need to reconecr to the camera?

**Comment by shaizae10** [comment]
import numpy as np
from matplotlib import pyplot as plt

from HW.vimba import Vimba


class Alvium1800:
    def __init__(self, exptier_time: float = 0.3):
        self.frame = None
        vimba = Vimba()
        with vimba.get_instance() as vimba:
            self.camera = vimba.get_all_cameras()
            if len(self.camera) == 1:
                self.camera = self.camera[0]
                with self.camera as cam:
                    self.features = cam.get_all_features()[0]
            elif len(self.camera) == 0:
                raise IOError("camera didn't detected")
            else:
                pass
            print()

    def initialize_communication(self):
        pass

    def take_single_measurement(self) -> np.ndarray:

        self.frame = self.camera.get_frame()

        # frame.
        return self.frame


if __name__ == "__main__":
    exampel = Alvium1800()
    frame = exampel.take_single_measurement()
    plt.imshow(frame)
    plt.show()

**Comment by shaizae10** [comment]
somting get rong whit the copy of the data

**Comment by Teresa-AlliedVision** [comment]
Hello,
please edit the code to show the right format, for Python the formatting shows cntext, so it is necessary. Try copying the code first, then select the text and then click the <> button. 
Other than that, please make sure that the camera.get_frame() command is within the with statement of Vimba, like for example so:
```
def take_single_measurement()->np.ndarray:
    with Vimba.get_instance():
        with self.camera:
        frame = self.camera.get_frame()
```
For reference on how to manage the with statement, you can also look at the code, that Niklas did in this issue: #143 
That code is for a different method of acquiring frames, so it is not an example you can use directly, but just to see how to structure the context witht he with statement.
```
  def _stream_frames(self):
      with vimba.Vimba.get_instance():
          with self.camera:
              self._stop_streaming_event.clear()
              _handler = FrameHandler(self.handler)
              self.camera.start_streaming(_handler)
              self._stop_streaming_event.wait()
              self.camera.stop_streaming()
```

**Comment by shaizae10** [comment]
tenx i'll fix the code  :)
there is no option to connect to the camera and then just read the buffer?
i have no need to live streem

**Comment by Teresa-AlliedVision** [comment]
Yes, of course you don't need to stream, you can keep with synchronous acquisition (get_frame()) to get one single image when you need it. That is why the second example is only for the structure of the def, not for the actual code. Because the example from Niklas uses asynchronous acquisition/streaming.
I'm not sure what you mean with reading the buffer.
Synchronous acquisition functions like this:

- You open the camera
- You tell the camera to send one image
- The camera starts to expose the sensor
- The camera takes one image
- The camera stops expoasng the sensor
- The camera sends one image
- You use the image/frame in your program

For an easier example, please use [synchronous_grab.py](https://github.com/alliedvision/VimbaPython/blob/master/Examples/synchronous_grab.py)  to see an implementation of getting frames synchronously (as you are doing right now).
