### ISSUE TITLE
Multithreading- Example doesn't stream! How to include frame handler?

### ISSUE THREAD

**Issue by venusgorilla** [alliedvision/VimbaPython#158]
I want to to use the multithreading example to continously stream two cameras. But executing the script only gives one static image of the camera. Can anyone give me a hint how to create a stream with the multithreading example? I already tried to include a frame handler from the other examples but I failed.

Thank you!

**Comment by BernardoLuck** [comment]
Hello, can you tell which cameras are you using and you comment on the modifications that you have done to the code?

**Comment by venusgorilla** [comment]
Both Cameras are Guppy Pro F-031.

I have discarded the modifications. So at the moment I'm still on the example code and try to understand all parts to figure out my problem. 

But is it intended that the sample code only takes a static image? When I look up the frame queue size it is always 0 except for the one image.

**Comment by venusgorilla** [comment]
@BernardoLuck  I solved the problem. Buffer count in cam.start_streaming() was set to 5 which was too low to get a stream. With a higher count it works.
