### ISSUE TITLE
Changing pixel formats.

### ISSUE THREAD

**Issue by wjun0830** [alliedvision/VimbaPython#18]
Hello.

There is no available pixel formats that is both compatible with Color and OpenCV.

Can you provide how to convert bayerRG pixel formats to opencv Umat or the image file so i can save the images in color?

**Comment by NiklasKroeger-AlliedVision** [comment]
Hi and sorry for the long wait.

Which camera model are you using? I was under the impression that vimba should be able to handle the transformation to RGB but currently I unfortunately do not have a color camera handy to test this.

Some research however showed that with `cv2.cvtColor(src_image, color_code)` you might be able to transform the image with the color code `cv2.COLOR_BayerRG2RGB`. For a full list of color conversion codes you can check [the opencv documentation](https://docs.opencv.org/4.3.0/d8/d01/group__imgproc__color__conversions.html).

I hope this helps.

**Comment by wjun0830** [comment]
I am using GT 1930C and now finally figured out using your python implementation. I think I missed how to control the frame object. Because of that, I couldn't use the cvtColor haha..
