### ISSUE TITLE
slow image acquisition

### ISSUE THREAD

**Issue by cnavarrete** [alliedvision/VimbaPython#22]
Hello

I'm trying to use an [ALVIUM 1800 U-501M NIR](https://www.alliedvision.com/en/products/embedded-vision-cameras/detail/Alvium%201800%20U/-501m%20NIR.html) camera to capture some frames on a Jetson Nano. The problem is that the image adquision is way too slow barely 5 FPS when tested on [synchronous_grab.py](https://github.com/alliedvision/VimbaPython/blob/master/Examples/synchronous_grab.py), while the details on the camera specify **Max. frame rate at full resolution: 67 fps at ≥350 MByte/s, Mono8**, so I'm a little puzzled about what's the problem. 
Also tried to switch the Jetson into MAXN mode but didn't help.

could you help me with this?

**Comment by NiklasKroeger-AlliedVision** [comment]
Generally speaking synchronous acquisition will not give you the best performance. You will achieve better results by using asynchronous acquisition as the buffer handling for new images is much more efficient. So perhaps try running [`asynchronous_grab.py`](https://github.com/alliedvision/VimbaPython/blob/master/Examples/asynchronous_grab.py) to see how much improvement this brings.

Additionally you might want to take a look at one of our Application notes: [USB Camera Handling - Linux](https://cdn.alliedvision.com/fileadmin/content/documents/products/cameras/various/appnote/USB/USB-camera-handling_Linux.pdf) More application notes can be found [on our website](https://www.alliedvision.com/en/support/technical-papers-knowledge-base.html)). Especially the sections 'Adapting the Vimba USB Transport Layer settings' and 'Adjusting DeviceLinkThrougputLimit' led to improved performance for me in the past. The default values here are chosen to provide a very stable stream. So be advised, that increasing them might come with an increase in incomplete frames if other devices are using the USB bus for communication at the same time.

I hope this helps. If you have further questions feel free to also contact our support via [the form on our website](https://www.alliedvision.com/en/support/contact-support-and-repair.html).

**Comment by cnavarrete** [comment]
Thanks a lo. I did some research and also followed your steps and I can finally reach 67 fps.
