### ISSUE TITLE
Unable to recover from crash

### ISSUE THREAD

**Issue by cnavarrete** [alliedvision/VimbaPython#31]
Here's my problem, I have 2 cams connected to my Jetson Xavier NX, and they were running just fine until an unexpected crash in one of my python apps, and now the 2 cams won't grab any frames  in the callback.

If I try to run the cams with modied parameters i.e. I modify the roi I get this message:
```
counter_arm64_1     | vimba.error.VimbaFeatureError: Invalid access while calling 'set()' of Feature 'Width'. Read access: allowed. Write access: allowed.
counter_arm64_1     | terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
counter_arm64_1     |   what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
```
I already tried to reboot but that didn't work, I also tried to delete the memory shared file in /dev/shm but I see that no longer applies. By the way I'm using vimba 4.2 arm64.

**Comment by NiklasKroeger-AlliedVision** [comment]
What kind of cameras are you using? USB or GigE? This feels like the Vimba System on the Jetson board assumes the camera is reachable (`Read access: allowed. Write access: allowed.`) but the camera itself refuses to accept the communication. Have you tried repowering the cameras as well? Please try unplugging their power source and plugging it back in.

> I also tried to delete the memory shared file in /dev/shm but I see that no longer applies

Yes the shared memory are was removed recently to prevent some edge cases where unexpected crashes led to similar behaviour on subsequent starts of Vimba. But as you also mentioned that you rebooted your board, there should not be any remnants of old connections on the host system. I assume the camera is in some unexpected state where it believes the old connection from before the crash to still be open.

Do you happen to also have any additional info on what kind of crash you experienced? Usually the context managers (`with cam: ...`) should prevent the cameras from ever entering such an unexpected state. Python exceptions should be caught with those. So it seems like something else must have happened.

If the error persists please feel free to also contact our support via [the form on our website](https://www.alliedvision.com/en/support/contact-support-and-repair.html). Perhaps they are able to assist further.

**Comment by cnavarrete** [comment]
I'm using the ALVIUM 1800 U-501M NIR usb cameras. About depowering the cameras, yes in the past this has been the solution, but I need something less invasive, since now my jetson is very far away and I can't send someone to depower the cameras whenever I want. 
Another problem, trying to set the devicethorughputlimit the following message appears:
`vimba.error.VimbaFeatureError: Called 'set()' of Feature 'DeviceLinkThroughputLimit' with invalid value. 65318400 is not within [32750000, 50000000].`
So now it's telling me to not use a value outside that range, weird.
By the way I should mentiion that I'm using a modified version of Vimba 4.2 for python 3.6, I just modified what you specified [here](https://github.com/alliedvision/VimbaPython/issues/16) , but anyway I have experienced the same exact problem using python 3.7, so I don't think it has anything to do with that.
Is depowering the cameras really the only solution?

**Comment by NiklasKroeger-AlliedVision** [comment]
> I need something less invasive, since now my jetson is very far away and I can't send someone to depower the cameras whenever I want.

You should also be able to power cycle the camera by executing the `DeviceReset` command feature:
```python
import vimba

with vimba.Vimba.get_instance() as vmb:
    with vmb.get_camera_by_id('<YOUR_DEVICE_ID_HERE>') as cam:
        cam.DeviceReset.run()
```

This should turn the camera off, removing it from the system bus and power it back on. This is essentially the same thing as unplugging and plugging it back in. I hope this fixes the issue!

> Another problem, trying to set the devicethorughputlimit the following message appears:
> `vimba.error.VimbaFeatureError: Called 'set()' of Feature 'DeviceLinkThroughputLimit' with invalid value. 65318400 is not within [32750000, 50000000].`
> So now it's telling me to not use a value outside that range, weird.

This is unexpected. Note that the upper limit in that error message is 50.000.000 (dots added as delimiter to make it easier to read). This means, that the maximum bandwidth available to that device is reported as 50MBit/sec. This is the speed of a USB2 connection. The Alvium cameras require USB3 connections to function properly. This would usually report a maximum bandwidth of 450.000.000 (450MBit/sec) (We reserve 10% of the maximum 500MBit/sec speed of USB3 connections for overhead). So there is definitely something up with the camera connection. Please try to perform the `DeviceReset` above.

> By the way I should mentiion that I'm using a modified version of Vimba 4.2 for python 3.6

I agree that this is likely not the cause of this error. With 3.6 you do however lose some type safety which could lead to incorrect use of the VimbaC API. I would suggest trying to use Python3.7 or above where possible. On the Jetson boards running Ubuntu18.04 you are able to install a Python3.7 interpreter from the official repositories. What is keeping you on 3.6? Perhaps there is a way to get you upgraded to an officially supported version of Python for VimbaPython.

**Comment by cnavarrete** [comment]
Hey that worked, all problems are gone now! Thanks, you are always a big help.
I'm working with docker so most containers (like pytorch) are tailor made for python3.6, theres a way to compile stuff for python3.7, but we have decided that it's not worth the effort at least for now.
