### ISSUE TITLE
Trigger problem with Alvium 1800 U-500m camera

### ISSUE THREAD

**Issue by marciojersey** [alliedvision/VimbaPython#32]
I am developing a Python app to trigger an Alvium 1800 U-500m camera to grab frames but am experiencing unusual behaviour. When using software triggers, it always take 2 triggers to get the camera to grab a frame. On the first trigger, the camera's status led transitions from being steady to a fast blinking. On the second software trigger, the led goes back to being steady and a frame is grabbed. The frame ID numbers are also coming in as even numbers. For instance, the first frame is frame 0, the second frame is frame 2 and so on. With hardware triggering, the first trigger causes the led to transition from steady to blinking but no frame is ever grabbed nor does the led go back to steady, no matter how many subsequent hardware triggers are made. My operating system is Ubuntu 20.0.4 and the camera is connected to a USB 3.0 port with a 1.0m cable. Here is example code I use for software triggering:

```
with Vimba.get_instance() as vimba:
    with vimba.get_camera_by_id(self.id) as c:
        c.AcquisitionMode.set('Continuous')
        c.TriggerSelector.set('FrameStart')
        c.TriggerMode.set('On')
        c.TriggerSource.set('Software')
        c.start_streaming(handler=frame_handler)
        for k in range(1,10):
            c.TriggerSoftware.run()
            print("Software trigger performed")
            times.sleep(1)
```

**Comment by marciojersey** [comment]
I switched ports on my computer and the problems went sway. The port I was using probably didn't have enough power.

**Comment by NiklasKroeger-AlliedVision** [comment]
Glad to hear that switching the USB port fixes this. That is definitely something I would not have though of. Thank you for updating (and closing) the issue!
