### ISSUE TITLE
no TL detected

### ISSUE THREAD

**Issue by skywo1f** [alliedvision/VimbaPython#33]
installed vimba successfully:
Installed /usr/local/lib/python3.6/dist-packages/VimbaPython-1.0.1-py3.6.egg
Processing dependencies for VimbaPython==1.0.1
Finished processing dependencies for VimbaPython==1.0.1

but still got:
   raise VimbaSystemError('No TL detected. Please verify Vimba installation.')
vimba.error.VimbaSystemError: No TL detected. Please verify Vimba installation.

**Comment by NiklasKroeger-AlliedVision** [comment]
Vimba is the name of the SDK for our Allied Vision cameras. VimbaPython on the other hand is a component of that SDK. This component exposes the functionality of the SDK as a Python package.

It seems like you installed VimbaPython into your Python3.6 installation. Now you are probably still missing the system wide Vimba installation, which would make our Transport Layers (TL for short) available by setting some environment variables. That is why you get the error message `No TL detected. Please verify Vimba installation.`

You can get the Vimba SDK as follows:
- Download the current version from [our website](https://www.alliedvision.com/en/products/software.html) (scroll down to the Downloads section)
- From your description I assume you are using Linux. This means you would need to download the release for Linux, and unpack that file. This will contain a `Vimba_4_2` directory which you can place on your system where you wish.
- Install the Transport Layer for the type of camera you want to use (VimbaUSBTL for USB cameras, VimbaGigETL for GigE cameras) by executing the `Install.sh` script in the corresponding directory (admin rights required so you might need to use `sudo`)
- Reboot your system and try to run your VimbaPython test script again.

If you have further questions feel free to also contact our support via [the form on our website](https://www.alliedvision.com/en/support/contact-support-and-repair.html) or comment here again.

**Comment by skywo1f** [comment]
viti@Epicrates:~/Downloads/Vimba_4_2/VimbaPython$ sudo ./Install.sh 
###############################
# VimbaPython install script. #
###############################
The following Python versions with pip support were detected:
  0: /usr/bin/python3.8
Enter python version to install VimbaPython (0 - 0, default: 0): 
Installing VimbaPython for /usr/bin/python3.8

Install VimbaPython with numpy support (yes/no, default: yes):
Installing VimbaPython with numpy support.

Install VimbaPython with OpenCV support (yes/no, default: yes):
Installing VimbaPython with OpenCV support.

WARNING: The directory '/home/iviti/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing ./Source
Requirement already satisfied: opencv-python in /usr/local/lib/python3.8/dist-packages (from VimbaPython==1.0.1) (4.5.1.48)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from VimbaPython==1.0.1) (1.20.1)
Building wheels for collected packages: VimbaPython
  Building wheel for VimbaPython (setup.py) ... done
  Created wheel for VimbaPython: filename=VimbaPython-1.0.1-py3-none-any.whl size=72303 sha256=c48905175cc99b26ad4ea3952dc277676e45a92bc19a7d26a422b655e73df676
  Stored in directory: /tmp/pip-ephem-wheel-cache-d1zosc85/wheels/43/c0/57/ed85f88aaede72de1570c20560c3323ca38006a3c4a518000d
Successfully built VimbaPython
Installing collected packages: VimbaPython
Successfully installed VimbaPython-1.0.1
VimbaPython installation successful.


:~/Downloads/Vimba_4_2/VimbaPython/Examples$ python3.8 list_cameras.py 
Traceback (most recent call last):
  File "list_cameras.py", line 28, in <module>
    from vimba import *
  File "/usr/local/lib/python3.8/dist-packages/vimba/__init__.py", line 103, in <module>
    from .vimba import Vimba
  File "/usr/local/lib/python3.8/dist-packages/vimba/vimba.py", line 30, in <module>
    from .c_binding import call_vimba_c, VIMBA_C_VERSION, VIMBA_IMAGE_TRANSFORM_VERSION, \
  File "/usr/local/lib/python3.8/dist-packages/vimba/c_binding/__init__.py", line 107, in <module>
    from .vimba_c import VmbInterface, VmbAccessMode, VmbFeatureData, \
  File "/usr/local/lib/python3.8/dist-packages/vimba/c_binding/vimba_c.py", line 674, in <module>
    _lib_instance = _check_version(_attach_signatures(load_vimba_lib('VimbaC')))
  File "/usr/local/lib/python3.8/dist-packages/vimba/c_binding/vimba_common.py", line 484, in load_vimba_lib
    return platform_handlers[sys.platform](vimba_project)
  File "/usr/local/lib/python3.8/dist-packages/vimba/c_binding/vimba_common.py", line 503, in _load_under_linux
    raise VimbaSystemError('No TL detected. Please verify Vimba installation.')
vimba.error.VimbaSystemError: No TL detected. Please verify Vimba installation.

**Comment by NiklasKroeger-AlliedVision** [comment]
That is the VimbaPython installation script. In the directories `~/Downloads/Vimba_4_2/VimbaUSBTL` and `~/Downloads/Vimba_4_2/VimbaGigETL` you can find the installation scripts for the transport layers. Please run the one suitable for the kind of camera you want to use and reboot your system.

Doing this will set the `GENICAM_GENTL64_PATH` environment variable (or `GENICAM_GENTL32_PATH if you are on a 32 bit system). You can verify this by running `env` after the reboot and checking if these variables are set with existing paths on your system.

**Comment by skywo1f** [comment]
ok, seems to be working now. thanks!
