### ISSUE TITLE
Exposure time&Gain

### ISSUE THREAD

**Issue by arielkantorovich** [alliedvision/VimbaPython#41]
Hello everyone,
I do not find in the methods of pymba how I can control the exposure time and the gain of the camera.
In addition, how can I acquire the information single frame, for example, 10 photographs and that the method returns to me a matrix of a column row and a dimension of ten, each dimension being a specific image.
Thanks to all the helpers :)

**Comment by NiklasKroeger-AlliedVision** [comment]
As you have closed the issue I assume you no longer need assistance with this. I would however like to point out, that this repository contains VimbaPython and not Pymba. VimbaPython is the name of our official Python API for the Vimba SDK. You can find examples on how to e.g. capture 10 images in our [`synchronous_grab.py` example](https://github.com/alliedvision/VimbaPython/blob/master/Examples/synchronous_grab.py). This will give you 10 images independent from one another. To get a larger array of 10 images in a single numpy array, you would need to place these images in an appropriate numpy array yourself.

If you want to use asynchronous image acquisition to get better performance you could take a look at our [`asynchronous_grab.py` example.](https://github.com/alliedvision/VimbaPython/blob/master/Examples/asynchronous_grab.py).
