### ISSUE TITLE
Error import vimba

### ISSUE THREAD

**Issue by arielkantorovich** [alliedvision/VimbaPython#42]
Hello everyone I installed the vimba sdk app I have python 3.8 on my computer and I still can't install the VimbaPython library through the pycharm so I can not import vimba I would be happy to help I do not understand why I can not install the library through the pip.

DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated and has no effect anymore. pip 21.1 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
ERROR: Could not find a version that satisfies the requirement VimbaPython
ERROR: No matching distribution found for VimbaPython

**Comment by NiklasKroeger-AlliedVision** [comment]
What steps are you performing to install VimbaPython for your python environment. We currently do not provide VimbaPython via the Python Package Index. Perhaps PyCharm is attempting to download from there and this is the reason for the `Could not find a version that satisfies the requirement VimbaPython` error.

Unfortunately it seems like PyCharm does not have an easy way to install Python packages from a local directory. What you probably need to do is pass the path to the VimbaPython directory that was included with your Vimba installation to pip. The most complete answer I was able to find describing how to do this is [this stackoveflow answer](https://stackoverflow.com/a/46141944/6748616):
- Load the PyCharm project you want to use VimbaPython with
- open PyCharms terminal (ALT+F12, or View > Tool Windows > Terminal)
- run the command `pip install /path/on/your/system/to/your/VimbaPython` (the exact path depends on where you unpacked Vimba to on Linux or can be found at `C:\Program Files\Allied Vision\Vimba_X.Y\VimbaPython\Source` on Windows where `X.Y` is your installed Vimba version)

This should install VimbaPython for the interpreter used in the PyCharm project. For some more information please follow the link to the actual stackoverflow answer above.
