### ISSUE TITLE
How to get color images through opencv？

### ISSUE THREAD

**Issue by DaniloXiao** [alliedvision/VimbaPython#49]
Hello, I am using an AVT GT2000c camera, but I found that the color pixel format of vimba cannot match the color pixel format of opencv. How can I get a color image?thank you very much.

1. cam.get_pixel_formats():(PixelFormat.Mono8, PixelFormat.BayerGB8, PixelFormat.BayerGB12, PixelFormat.BayerGB12Packed)
2. OPENCV_PIXEL_FORMATS:(PixelFormat.Mono8, PixelFormat.Bgr8, PixelFormat.Bgra8, PixelFormat.Mono16, PixelFormat.Bgr16, PixelFormat.Bgra16)

**Comment by NiklasKroeger-AlliedVision** [comment]
The easiest way is probably to simply record your images with the supported `BayerGB8` and use OpenCV immediately to convert that raw data into RGB data. Here is an example of how you can do that.

```python
import vimba
import cv2

with vimba.Vimba.get_instance() as vmb:
    cams = vmb.get_all_cameras()
    with cams[0] as cam:
        # Adjust to the Bayer format you want to use
        cam.set_pixel_format(vimba.PixelFormat.BayerGB8)
        # Record single frame for this example
        frame = cam.get_frame()
        # Get the raw image data as numpy array from the frame
        image = frame.as_numpy_ndarray()
        # Use opencv to convert raw Bayer image to RGB image
        rgb_image = cv2.cvtColor(image, cv2.COLOR_BAYER_GB2RGB)
        cv2.imshow("test", rgb_image)
        cv2.waitKey(0)
```

The alternative would be to use the transformation we include in our ImageTransform library, but since you want to use the images with OpenCV this is probably more convenient for you.

**Comment by DaniloXiao** [comment]
Thank you for helping me solve the problem.

**Comment by DaniloXiao** [comment]
> The easiest way is probably to simply record your images with the supported `BayerGB8` and use OpenCV immediately to convert that raw data into RGB data. Here is an example of how you can do that.
> 
> ```python
> import vimba
> import cv2
> 
> with vimba.Vimba.get_instance() as vmb:
>     cams = vmb.get_all_cameras()
>     with cams[0] as cam:
>         # Adjust to the Bayer format you want to use
>         cam.set_pixel_format(vimba.PixelFormat.BayerGB8)
>         # Record single frame for this example
>         frame = cam.get_frame()
>         # Get the raw image data as numpy array from the frame
>         image = frame.as_numpy_ndarray()
>         # Use opencv to convert raw Bayer image to RGB image
>         rgb_image = cv2.cvtColor(image, cv2.COLOR_BAYER_GB2RGB)
>         cv2.imshow("test", rgb_image)
>         cv2.waitKey(0)
> ```
> 
> The alternative would be to use the transformation we include in our ImageTransform library, but since you want to use the images with OpenCV this is probably more convenient for you.

Thank you for helping me solve the problem.
