### ISSUE TITLE
First example of the documentation on page 11

### ISSUE THREAD

**Issue by ttamttam** [alliedvision/VimbaPython#5]
Revision : c888379951f1f3ecfcfa5d7380dfbba862e582b2

I had to replace `VimbaPixelFormat` with `PixelFormat` for this example to work.

Best regards

**Comment by NiklasKroeger-AlliedVision** [comment]
Great catch! Thank you for pointing that out to us!

**Comment by NiklasKroeger-AlliedVision** [comment]
I just updated the repository with the official release of version 1.0.0 and the documentation was updated accordingly. We also fixed the usage of `PixelFormat` in the provided examples. Again, thank you for pointing the error out to us!
