### ISSUE TITLE
Read out the exposure time

### ISSUE THREAD

**Issue by ericyuanhhh** [alliedvision/VimbaPython#58]
I try to get the exposure time of my camera following the documentation. I use `exposure_time = cam.ExposureTime`. However I get the error: 'Camera' object has no attribute 'ExposureTime'. It seems an easy problem to solve but I cannot figure it out. Thank you!

**Comment by ericyuanhhh** [comment]
The camera I am using is Mako-G-503B

**Comment by NiklasKroeger-AlliedVision** [comment]
Are you sure that you are trying to access the camera feature from within a `with` block that opens the camera connection? The Camera features are registered as properties when the camera connection is opened by entering the `with` block. Here is a quick example on how you may access the camera feature `ExposureTime`:

```python
import vimba

with  vimba.Vimba.get_instance() as vmb:
    with vmb.get_all_cameras()[0] as cam:
        # Accessing Features as Objects
        print(cam.ExposureTime.get())
        # Alternative: Using get_feature_by_name. Gives the same result
        print(cam.get_feature_by_name("ExposureTime").get())
```

Please try running this to see if your the exposure time of your camera is printed successfully.

For some older camera models it is also possible, that the camera features do not follow the GenICam Standard Feature Naming Convention completely. For these models other  Feature names such as `ExposureTimeAbs` may be what you want. However I just used the code example above with a Mako U503B and it worked as expected. So I do not think that is the problem you are facing. If you want to see what features are available on your camera the [`list_features.py`](https://github.com/alliedvision/VimbaPython/blob/916ed0561139f7c45b15e697c19c8b60ba0a19f4/Examples/list_features.py) example is probably a good place to start.

**Comment by ericyuanhhh** [comment]
The list_features.py is very helpful. For my camera, the feature I need is "ExposureTimeAbs". Thank you!
