### ISSUE TITLE
Is there a way to get the Offset Range available?

### ISSUE THREAD

**Issue by rk-exxec** [alliedvision/VimbaPython#61]
I ran into an issue when selecting a ROI that gets close to the upper image border.  

I always get this error:
`vimba.error.VimbaFeatureError: Called 'set()' of Feature 'OffsetY' with invalid value. 1216 is not within [0, 1214].`

Is there a way to read the range that is returned by the error before setting the offset?

**Comment by NiklasKroeger-AlliedVision** [comment]
Yes for the `IntFeature` and `FloatFeature` class there is a method named `get_range()` that returns a tuple with the min and max value:
```python
import vimba

with vimba.Vimba.get_instance() as vmb:
    with vmb.get_all_cameras()[0] as cam:
        min_value, max_value = cam.OffsetY.get_range()
        print(f'Minimum: {min_value}, Maximum: {max_value}')
```

For the `OffsetY` feature (and many others) it is important to consider, that their possible values can be affected by the values of other features. If the `Height` of the recorded image is the full sensor height, `OffsetY` for example can only be 0.

**Comment by rk-exxec** [comment]
Thanks for the quick response!
The values returned by get_range() still need to be adjusted to be a multiple of 8, is this intentional?

**Comment by NiklasKroeger-AlliedVision** [comment]
That is necessary because the used camera sensor might not allow readout to begin at arbitrary positions. You can get the so called increment in which the values may be set from the feature as well by using the `get_increment()` method (sorry I forgot to mention this in the last example...):
```python
import vimba

with vimba.Vimba.get_instance() as vmb:
    with vmb.get_all_cameras()[0] as cam:
        min_value, max_value = cam.OffsetY.get_range()
        increment = cam.OffsetY.get_increment()
        print(f'Minimum: {min_value}, Maximum: {max_value}, Increment: {increment}')
```

For my camera (Alvium 1800 U-500m) this gives these values (yours depend on the camera model and e.g. the set `Width` and `Height` feature values):
```
Minimum: 0, Maximum: 972, Increment: 2
```

This means the following values are allowed to be set : `[0, 2, 4, 6, ..., 966, 968, 970, 972]`

**Comment by rk-exxec** [comment]
So I implemented my new method with the info you've given me.

(I initialized self._vimba and self._cam beforehand)
```python
def set_roi(self, xo, yo, w, h):
    with self._vimba:
        with self._cam:
            self._cam.OffsetX.set(0)
            self._cam.OffsetY.set(0)

            w_step = self._cam.Width.get_increment()
            h_step = self._cam.Height.get_increment()
            w_min, w_max = self._cam.Width.get_range()
            h_min, h_max = self._cam.Height.get_range()
    
            # check if value is n*stepsize larger than minimum
            # rounds down to nearest valid value
            w = (w - w_min) // w_step * w_step + w_min
            h = (h - h_min) // h_step * h_step + h_min
            # limit value to range
            w = max(w_min, min(w_max, w))
            h = max(h_min, min(h_max, h))

            self._cam.Width.set(w)
            self._cam.Height.set(h)

            xo_step = self._cam.OffsetX.get_increment()
            yo_step = self._cam.OffsetY.get_increment()
            xo_min, xo_max = self._cam.OffsetX.get_range()
            yo_min, yo_max = self._cam.OffsetY.get_range()

            xo = (xo - xo_min) // xo_step * xo_step + xo_min
            yo = (yo - yo_min) // yo_step * yo_step + yo_min
            xo = max(xo_min, min(xo_max, xo))
            yo = max(yo_min, min(yo_max, yo))

            self._cam.OffsetX.set(xo)
            self._cam.OffsetY.set(yo)
```

Would it be better to check the range before the step size or after? Or are the range limits guaranteed valid values?

**Comment by NiklasKroeger-AlliedVision** [comment]
From my quick checking it looks like your code works as intended.

> Would it be better to check the range before the step size or after? Or are the range limits guaranteed valid values?

The limits are values that you are allowed to set. The provided range is inclusive. I think the order in which you check should not make any difference.

**Comment by rk-exxec** [comment]
Alright, thank you very much for your help!
