### ISSUE TITLE
EXPECTED_VIMBA_C_VERSION 1.8.3 incompatible with latest Vimba (5.0) SDK

### ISSUE THREAD

**Issue by gtmaskall** [alliedvision/VimbaPython#64]
VimbaPython (this repo) latest release is 1.0.1 November 2020.
In vimba/c_binding/vimba_c.py, it states EXPECTED_VIMBA_C_VERSION is 1.8.3.
However, the latest Vimba SDK is [version 5.0](https://downloads.alliedvision.com/ReleaseNotes_Vimba_v5.0_Linux.txt).
Vimba 5.0 provides version 1.8.5 of the C API.

Thus if I install the latest released VimbaPython and the latest released Vimba SDK, I get an error that 1.8.3 is expected but it's found 1.8.5. I can't find hide nor hair of an older Vimba to download that might provide 1.8.3. But based on a comment on issue #43, I edited the string in vimba_c.py to expect 1.8.5. The Python wrapper was then happy and an initial check found that our code indeed could talk to the camera and pull data, so it seems to work.

Shouldn't VimbaPython be updated to keep up with the Vimba SDK, or is there a good reason to use an older, 4.x version with VimbaPython?

**Comment by arunprakash-avt** [comment]
This issue we are working on it. 
Yes please install the new VimbaPython sdk from Vimba 5.0.  The new version of Vimba 5.0 has some bug fixes. For this please refer to the release note of vimba 5.0

**Comment by NiklasKroeger-AlliedVision** [comment]
Thank you for pointing this out to us! It seems we have indeed forgotten to update the code in this repository.

You can however find a compatible version of VimbaPython as part your Vimba 5.0 installation. In the downloaded `Vimba_v5.0_Linux.tgz` there is a directory named `VimbaPython/Source`. This contains the version of VimbaPython that is compatible with the packaged VimbaC version.

The fix you implemented (updating expected VimbaC version) works, but the VimbaPython provided with Vimba 5.0 also contains some other minor changes. I would suggest that you use that version.

Sorry for the confusion. I will make sure that this repository is updated as quickly as possible.

**Comment by NiklasKroeger-AlliedVision** [comment]
Pushed [VimbaPython version 1.1.0](https://github.com/alliedvision/VimbaPython/releases/tag/v1.1.0) to the repository. This version is compatible and was already released with Vimba 5.0

Again, thank you for pointing this out!
