### ISSUE TITLE
Collecting images at multiple exposures for HDR

### ISSUE THREAD

**Issue by arpit15** [alliedvision/VimbaPython#66]
Camera : Prosilica GX 1910
Vimba SDK version : 5.0_Linux
Ubuntu : 20.04

I am using the following script to dump frames to a tiff file to create an HDR. I notice that sometimes the image obtained has a significantly lower intensity than its left neighbors(lower exposure value). I have tried to set the following features to make sure camera Exposure is set to the specified value at the time of frame grab. Please find the images collected using the following script [here](https://drive.google.com/drive/folders/1ZijSoyFkoqUc3gKGnj4Ct1pyEzVoXtms?usp=sharing). In this stack exposure values `27384000` ms and `54384000` ms images have suddenly lower intensity than previously captured images.  

Can you kindly suggest steps to collect images in which the radiance increases linearly with the exposure value of the camera?

1. `GainAuto` - `Off`
2. `ExposureAuto` - `Off`
3. `IrisMode` - `Disabled`
4. `GainRaw` - `20`
5. `ExposureTimeAbs` - specified in the loop
6. `timeout_ms` - specified equal to `ExposureTimeAbs` in the loop.
```
# Synchronous grab
from vimba import *
from skimage.io import imsave
from os.path import join
from apply_metadata import apply_metadata
import os

folder = os.path.expanduser("~/prosilica_cam_setup/check_exposure_range")
# wv = 450
# wv = 532
wv = 660
base = f"trial-{wv}"

exposure_list = []


for i in range(48):
    exposure_list.append(int(2**14*1e3 + i*1e6))

# exposure_list.append(int(1000*(2**15)))

with Vimba . get_instance () as vimba :
    cams = vimba. get_all_cameras ()
    with cams [0] as cam:
        # set_trace()
        exposure_min, exposure_max = cam.ExposureTimeAbs.get_range()
        cam.GainAuto.set("Off")
        cam.ExposureAuto.set("Off")
        cam.IrisMode.set("Disabled")
        cam.GainRaw.set(20)
        print(f"Minimum exposure time is {exposure_min}, Maximum exposure time is {exposure_max}")

        cam.set_pixel_format(PixelFormat.Mono14)
        for i in range(len(exposure_list)):
            exp = exposure_list[i]
            print(f"Dumping {exp} image")

            cam.ExposureTimeAbs.set(exp+0.0)
            # Aquire single frame synchronously
            frame = cam. get_frame (timeout_ms=exp).as_numpy_ndarray()
            # print(frame.max())
            fn = join(folder, f"{base}_{exp}.tiff")
            imsave(fn, frame)
            apply_metadata(fn, fn)
```

**Comment by NiklasKroeger-AlliedVision** [comment]
Hmmm it seems like there is some image data inside the mentioned tiff files. I downloaded them and using for example [ImageJ](https://imagej.nih.gov/ij/) or [Fiji](https://imagej.net/software/fiji/downloads) I am able to see the checkerboard pattern in the `27384000` and `54384000` images:
![image](https://user-images.githubusercontent.com/61547504/130739597-658402f9-d780-47ce-8093-faf83357baf2.png)

Maybe this is mainly a display problem with the viewer you are using? The camera seems to work as intended and delivers image data...

One thing that bothers me however is the fact, that the image becomes darker when going from exposure time `26384000` to `27384000`. This should not be the case unless you are doing something else that leads to less light hitting the camera sensor or modifying e.g. the gain value. Left histogram is calculated from image for exposure time `26384000`, right histogram for image with exposure time `27384000`.
![image](https://user-images.githubusercontent.com/61547504/130742470-94ddb289-32d0-4f8b-9717-6c8b2d01b578.png)

I have no idea what might be causing this problem. perhaps it is related to the way the images are saved? Does `skimage` attempt to perform some histogram normalization when saving the image? If you are only using the pixel data inside python, it might be worth to take a look into saving the numpy array directly. That way you can be sure, that no image processing or adjustment is done while saving the image data. Numpy [provides a `save` function](https://numpy.org/doc/stable/reference/generated/numpy.save.html) for that.

Lastly I want to point out, that you are never checking the status of the frame you received. Generally it would be good practice to make sure, that you have a `Complete` frame, before you use it. This can be done for example like this:
```python
frame = cam. get_frame(timeout_ms=exp)
if frame.get_status() == FrameStatus.Complete:
    img = frame.as_numpy_ndarray()
    # use img to work with the pixel data
```

You would then use the `img` variable which contains the pixel data as numpy array. The `else` case is left up to you. Maybe you want to throw an error or initiate a retry for that image... Whatever seems appropriate for you.

**Comment by arpit15** [comment]
I am not changing anything in the setup between captures. I made following changes based on your advice
1. Dumped images as `npy` as well as `tiff` images. 
![check_exposure_vals](https://user-images.githubusercontent.com/4703676/130809699-3e4244d1-4117-4b99-9962-b969e84e634f.png)
I still notice the same problem
2. Checked if the `imsave` is performing any histogram normalization. It is not
3. Check if the `FrameStatus`. I didn't notice any failure in captures. 

I visualize images using ubuntu native image viewer. I have uploaded the npy and tiff images [here](https://drive.google.com/drive/folders/1ZijSoyFkoqUc3gKGnj4Ct1pyEzVoXtms?usp=sharing). Do you have some other suggestions for debugging? I notice the problem is not specific to specific exposure values. They seem to happen randomly after using the camera for some time continuously.

**Comment by arpit15** [comment]
After consulation with the technical team, the problem is in the firmware of Prosilica GX 1910. The technical person was able to reproduce the bug on their end as well. As the camera is out of production, the company doesn't plan to correct the bug. 
The problem is that camera get reset as soon as you try to expose it for more than 27 seconds in freerun mode(without any external trigger). 
The workaroud which company person suggested was to use exteral trigger for setting exposure. I haven't tested the workaround as I don't have access to trigger kit. 
Feel free to close the issue.
