### ISSUE TITLE
No TL detected when using vimba python remote over ssh

### ISSUE THREAD

**Issue by lukazso** [alliedvision/VimbaPython#68]
Hey guys,

I encountered a strange behavior. We have 4 AlliedVision cameras connected to a Nvidia Jetson AGX Xavier. For development we work remotely on the Jetson via ssh. When I try to run my program on the Jetson via the remote terminal I get the error `vimba.error.VimbaSystemError: No TL detected. Please verify Vimba installation.` (similar so issue #33). However, when executing the program directly on the Jetson (no remote connection) it works perfectly fine. Do you know what could cause this behavior? For us it is extremely important to be able to execute or scripts remotely.

If it is of any importance, we are using Python 3.7.5.

Thanks,
Lukas

**Comment by NiklasKroeger-AlliedVision** [comment]
Hi Lukas,

that sounds like you are running into the problem of interactive and non-interactive sessions sourcing different configuration files. By default if an interactive login session is started, your system will source some configuration files (according to [[1]] this seems to be `/etc/profile` followed by `~/.bash_profile`). For non-interactive sessions different files are read (according to [[1]] `/etc/bash.bashrc` followed by `~/.bashrc`)

The Vimba installation on Linux works by adding files for our transport layers defining the `GENICAM_GENTL64_PATH` variable (or `GENICAM_GENTL32_PATH` depending on your systems architecture) to `/etc/profile.d`. The easiest way I see to get that variable set correctly on non-interactive sessions would be to simply source the appropriate file for the transport layer you want to use. You should be able to do so by simply adding `source /etc/profile.d/filenam-for-tl-you-want-to-use` to one of the configuration files that is being loaded on non-interactive sessions. An easy way to verify if the variable has been set is to run the `env` command from a non-interactive ssh command and check to see if the output includes the `GENICAM_GENTL64_PATH` variable.

Let me know if you have trouble setting this up. I could try replicating the problem on my system to give more specific instructions.

[1]: https://unix.stackexchange.com/a/332533

**Comment by lukazso** [comment]
Awesome, I added the line to my `.zshrc` and now it works perfectly fine. Thanks for the quick support!

**Comment by vantainguyen** [comment]
> Awesome, I added the line to my `.zshrc` and now it works perfectly fine. Thanks for the quick support!

Hi Lukas, which line did you add?

**Comment by vantainguyen** [comment]
> Hi Lukas,
> 
> that sounds like you are running into the problem of interactive and non-interactive sessions sourcing different configuration files. By default if an interactive login session is started, your system will source some configuration files (according to [[1](https://unix.stackexchange.com/a/332533)] this seems to be `/etc/profile` followed by `~/.bash_profile`). For non-interactive sessions different files are read (according to [[1](https://unix.stackexchange.com/a/332533)] `/etc/bash.bashrc` followed by `~/.bashrc`)
> 
> The Vimba installation on Linux works by adding files for our transport layers defining the `GENICAM_GENTL64_PATH` variable (or `GENICAM_GENTL32_PATH` depending on your systems architecture) to `/etc/profile.d`. The easiest way I see to get that variable set correctly on non-interactive sessions would be to simply source the appropriate file for the transport layer you want to use. You should be able to do so by simply adding `source /etc/profile.d/filenam-for-tl-you-want-to-use` to one of the configuration files that is being loaded on non-interactive sessions. An easy way to verify if the variable has been set is to run the `env` command from a non-interactive ssh command and check to see if the output includes the `GENICAM_GENTL64_PATH` variable.
> 
> Let me know if you have trouble setting this up. I could try replicating the problem on my system to give more specific instructions.

Hi there, I'm facing the same issue with my AGX Orin; what should I added and where please?
