### ISSUE TITLE
How to put the code about features

### ISSUE THREAD

**Issue by JackinMS** [alliedvision/VimbaPython#70]
ubuntu 18,04
tensorflow 2.3
opencv 4.5

with Vimba.get_instance() as vimba:
   cams = vimba.get_all_cameras()
   with cams[0] as cam:
       while True:
            frame = cam.get_frame()
            frame = frame.as_numpy_ndarray()
            frame = cv2.cvtColor(frame, cv2.COLOR_BARYER_GR2BGR)
            input_tensor = tf.convert_to_tensor(np.expand_dims(frame, 0), dtype=tf.float32)
           ....
           cv2.imshow("object detection", image_np_with_detections)

----------------------------------------------------------

I am using mako G-507B Gige now.
I have been trying to do two problems:
  1. Control or fix the values about gamma, Gain, Exposure in the code.
    - I saw all files but I do not have a idea that how can I put value about control gamma, Gain to the code.
      I did list_features.py. so I know that there are a lot of features. I want to use those features manually in the code.
      Could you give me a example about the code? 

  2. Error.
    - During streaming, there is an error : 
      vimba.error.VimbaTimeout : Frame capturing on Camera "DEV_000F315C555D' timed out.
      This error happened often with different time. For example, it happened in 5secs after streaming. but sometimes it happend
      in few hour after streaming. Could you let me know which part is the matter about it?

Thank you

**Comment by arunprakash-avt** [comment]
This is possible with Vimba Python. Please find below the reply for your questions as follows
1. To set the features, please use the below structure 
 cam.featureName.set(Value)
 Example:
Cam.Gain.set(10)
To get the proper featureName and value range please check the following link
https://cdn.alliedvision.com/fileadmin/content/documents/products/cameras/various/features/GigE_Features_Reference.pdf
2. The timeout is because of faulty camera settings. Is it possible to explain the following
•	The Network topology i.e how is the camera are connected?
•	If a Network card is used please mention the manufacture name and model number.
•	If a Switch is used what type of switch is used?

**Comment by JackinMS** [comment]
> This is possible with Vimba Python. Please find below the reply for your questions as follows
> 
> 1. To set the features, please use the below structure
>    cam.featureName.set(Value)
>    Example:
>    Cam.Gain.set(10)
>    To get the proper featureName and value range please check the following link
>    https://cdn.alliedvision.com/fileadmin/content/documents/products/cameras/various/features/GigE_Features_Reference.pdf
> 2. The timeout is because of faulty camera settings. Is it possible to explain the following
>    •	The Network topology i.e how is the camera are connected?
>    •	If a Network card is used please mention the manufacture name and model number.
>    •	If a Switch is used what type of switch is used?

**Comment by JackinMS** [comment]
Thank you for your kind reply.

#1 is works very well! but there is a problem that I used the code in my python file:
   cam.Width.set(800)
   cam.Height.set(600)
  and it works very well. Then, I terminated the python file and start the VimbaViewer. But Viewer shows the streaming with same setting(width 800, height 600) as python. So, I have no idea why it works like that. 
![Screenshot from 2021-09-14 17-20-33](https://user-images.githubusercontent.com/74068140/133225742-3c65b127-00ea-4e99-a39b-1b8d2b97a4e3.png)


#2 
 I don't use any switch or Hub. I used the desktop(i5-4690K, GTX 1060 3Gb, 16Gb, Ubuntu 16.04). 
My network(LAN) is Realtek 8111GR 1 x Gigabit LAN Controler in the motherboard(ASUS H97M-E).
I am using LAN port for camera and using internet by wifi connector looks like small usb.
When I use Camera, Internet is gone and I need to restart computer to use internet.
It is my Network and camara setting now.
![Screenshot from 2021-09-14 17-21-45](https://user-images.githubusercontent.com/74068140/133225852-cc087c68-09f2-4f45-8b4c-f841de02abec.png)

Thank you very much for your service.

**Comment by JackinMS** [comment]
Thank you for great answer and solution.
I am doing the next stage for object detection.
