### ISSUE TITLE
python installation error VIMBA_HOME

### ISSUE THREAD

**Issue by RICXS** [alliedvision/VimbaPython#74]
Hi,
I have just installed the VIMBA python API as described in the docs. I am using windows 7. After doing a ```python -m pip install.``` in the python source directory I get:
```
Processing c:\program files\allied vision\vimba_5.0\vimbapython\source
Building wheels for collected packages: VimbaPython
  Building wheel for VimbaPython (setup.py) ... done
  Created wheel for VimbaPython: filename=VimbaPython-1.1.0-py3-none-any.whl siz
e=72624 sha256=4057492e21a3756f21436389c1c7b82d9d4bf48d75d8a58e969a1453def2fe11
  Stored in directory: C:\Users\LOCAL_~1\AppData\Local\Temp\pip-ephem-wheel-cach
e-pkft7ruc\wheels\ea\9d\e3\da7e8b38258de7436ab58d116e25d44c2daba21598af6bd0eb
Successfully built VimbaPython
Installing collected packages: VimbaPython
  Attempting uninstall: VimbaPython
    Found existing installation: VimbaPython 1.1.0
    Uninstalling VimbaPython-1.1.0:
      Successfully uninstalled VimbaPython-1.1.0
Successfully installed VimbaPython-1.1.0
```

Then when I try to import vimba I get:
```
In [1]: import vimba
---------------------------------------------------------------------------
VimbaSystemError                          Traceback (most recent call last)
<ipython-input-1-a8b351bfe234> in <module>
----> 1 import vimba

C:\Program Files\Allied Vision\Vimba_5.0\VimbaPython\Source\vimba\__init__.py in
 <module>
    101
    102 # Import everything exported from the top level module
--> 103 from .vimba import Vimba
    104
    105 from .camera import AccessMode, PersistType, Camera, CameraChangeHandler
, CameraEvent, FrameHandler

C:\Program Files\Allied Vision\Vimba_5.0\VimbaPython\Source\vimba\vimba.py in <m
odule>
     28 import threading
     29 from typing import List, Dict, Tuple
---> 30 from .c_binding import call_vimba_c, VIMBA_C_VERSION, VIMBA_IMAGE_TRANSF
ORM_VERSION, \
     31                        G_VIMBA_C_HANDLE
     32 from .feature import discover_features, FeatureTypes, FeaturesTuple, Fea
tureTypeTypes, EnumFeature

C:\Program Files\Allied Vision\Vimba_5.0\VimbaPython\Source\vimba\c_binding\__in
it__.py in <module>
    105                           _select_vimba_home
    106
--> 107 from .vimba_c import VmbInterface, VmbAccessMode, VmbFeatureData, \
    108                    VmbFeaturePersist, VmbFeatureVisibility, VmbFeatureFl
ags, VmbFrameStatus, \
    109                    VmbFrameFlags, VmbVersionInfo, VmbInterfaceInfo, VmbC
ameraInfo, VmbFeatureInfo, \

C:\Program Files\Allied Vision\Vimba_5.0\VimbaPython\Source\vimba\c_binding\vimb
a_c.py in <module>
    672
    673
--> 674 _lib_instance = _check_version(_attach_signatures(load_vimba_lib('VimbaC
')))
    675
    676

C:\Program Files\Allied Vision\Vimba_5.0\VimbaPython\Source\vimba\c_binding\vimb
a_common.py in load_vimba_lib(vimba_project)
    482         raise VimbaSystemError(msg.format(sys.platform))
    483
--> 484     return platform_handlers[sys.platform](vimba_project)
    485
    486

C:\Program Files\Allied Vision\Vimba_5.0\VimbaPython\Source\vimba\c_binding\vimb
a_common.py in _load_under_windows(vimba_project)
    551
    552     if vimba_home is None:
--> 553         raise VimbaSystemError('Variable VIMBA_HOME not set. Please veri
fy Vimba installation.')
    554
    555     load_64bit = True if (platform.machine() == 'AMD64') and _is_python_
64_bit() else False

VimbaSystemError: Variable VIMBA_HOME not set. Please verify Vimba installation.
```

I am working not in the base environment but in my own. However, I checked that I have the correct versions of python, etc. in this environment.

1. Where is VIMBA_HOME set? 
2. Is it an evironment variable? 
3. Can I do this manually?

Thanks,
Karl

**Comment by NiklasKroeger-AlliedVision** [comment]
Hi Karl,

VimbaPython is essentially just a wrapper around our VimbaC API. It works by loading the VimbaC.dll  and "translating" you Python function calls to the appropriate VimbaC function call. In order to use VimbaPython you therefore also need to have VimbaC available on your system. It is not included in the VimbaPython installation.

You need to download the latest Vimba SDK release from [our website](https://www.alliedvision.com/en/support/software-downloads/). In this case that would be Vimba5.0 for Windows. This will Install VimbaC and our Transport layers on your system. It will also take care of setting the `VIMBA_HOME` environment variable for you (the variable will point to your Vimba installation directory and is how we locate VimbaC.dll on Windows).

**Comment by Nerverfail** [comment]
Hi,
I've installed Vimba 5.0 with everything in it checked. And I've installed VimbaPython as well.
However, it still gives me VIMBA_HOME not set error. 
I've tried manually setting VIMBA_HOME to the directory of VIMBA5.0 folder. It still says the same error when I try to import it. Could you walk me through what I need to do to actually make it work?
I'm trying to record videos using my Priscilla GT2000 camera with a Python interface. It just doesn't work.

**Comment by arunprakash-avt** [comment]
For further support can you please write us an email to support@alliedvision.com.

**Comment by acoathup** [comment]
I am having a similar issue also related to VIMBA_HOME aparently. Did you end up finding out how to proceed?

**Comment by arunprakash-avt** [comment]
Hi, 
I would like to know if your are using Linux or Windows?
As Vimba python is a wrapper from VimbaC. Vimba should be installed properly to install VmbaC, then VIMBA_HOME will be created automatically.
In Windows this can be verified by checking the Environmental Varialble VIMBA_HOME.

**Comment by acoathup** [comment]
Hi,
Thanks for your reply. I am using Windows. I checked the Environmental Variables and it's true that I don't see the VIMBA_HOME so I assume that the Vimba wasn't installed correctly. Although, the camera itself and the program to display the image seems to work.

**Comment by yytkoukoutang** [comment]
I found that if you do not give the cmd an Administrator  rights, the problem will apeear.
I open the cmd as administrator and install the vimbapython again, and than the problem is fixed.
