### ISSUE TITLE
Bugfix poor performance with frame generator

### ISSUE THREAD

**Issue by aphilip442** [alliedvision/VimbaPython#79]
Hi,

I am interfacing with a Mako camera using the VimbaPython 5.0 API.
I noticed a serious performance issue in the _frame_generator function (accessed through get_frame_generator method), which prevents the camera from reaching requested framerates (it would basically top out at 30fps no matter what).

Here is a fix: enter the capturing mode once at the start, and exit it at the end, instead of entering/exiting for each frame yielded.

```
@TraceEnable()
def _frame_generator(cam, limit: Optional[int], timeout_ms: int):
    if cam.is_streaming():
        raise VimbaCameraError('Operation not supported while streaming.')

    frame_data_size = cam.get_feature_by_name('PayloadSize').get()
    frames = (Frame(frame_data_size), )
    fsm = _CaptureFsm(_Context(cam, frames, None, None))
    cnt = 0

    try:
        # Enter Capturing mode
        exc = fsm.enter_capturing_mode()
        if exc:
            raise exc

        while limit is None or cnt < limit:
            fsm.wait_for_frames(timeout_ms)

            # Return copy of internally used frame to keep them independent.
            frame_copy = copy.deepcopy(frames[0])
            frame_copy._frame.frameID = cnt
            cnt += 1

            yield frame_copy

    finally:
        # Leave Capturing mode
        exc = fsm.leave_capturing_mode()
        if exc:
            raise VimbaCameraError from exc
```

You will notice that I raise a VimbaCameraError in the closing part of the generator.
For some reason, it would throw a "vimba.error.VimbaCameraError: <VmbError.Other: -13>" upon closing the generator.
I catch and silence it in my application, as it does not appear critical.

You might want to fix that cleanly, as this is seriously impacting the Python API performance to the point of making it basically unusable in this use case.

**Comment by aphilip442** [comment]
Thank you for your answer!
If issues arise I will use the async way!

**Comment by NiklasKroeger-AlliedVision** [comment]
> If issues arise I will use the async way!

Feel free to open an issue if you run into problems with that. Again thank you for the good suggestion!
