### ISSUE TITLE
Vimba Hangs on call_vimba_c('VmbShutdown')

### ISSUE THREAD

**Issue by shornett** [alliedvision/VimbaPython#8]
Occasionally after a crash the vimba hangs on exit until the computer has been power cycled. 

In this minimal example it never reaches the print("ended") statment 
```
with Vimba.get_instance() as vimba:
    print(vimba.get_all_cameras())
print("Ended")
```

On debugging it hangs forever on ` call_vimba_c('VmbShutdown')` in the `Vimba._shutdown` method. And does this for all the examples the only way to restore functionality is to restart the system. 
Logging out does not fix the error.
dmesg shows that the cameras are being redetected on disconnection and reconnection
 
Running Vimba 4_0_0 , Ubuntu 20.04

Thanks

**Comment by shornett** [comment]
Thanks for getting back to me. I agree with your assessment, I suspect the issue is with an interaction between the USB transport layer and ubuntu.

**Comment by nordeh** [comment]
Vimba locks USB cameras by shared memory objects. Delete the temporary files to release the camera after a crash: /dev/shm/3*
Please refer to our USB appnote:
https://cdn.alliedvision.com/fileadmin/content/documents/products/cameras/various/appnote/USB/USB-camera-handling_Linux.pdf#page=3

**Comment by shornett** [comment]
This works for the time being. thanks for the reply.
