### ISSUE TITLE
Getting AcquisitionFrameRateLimit 

### ISSUE THREAD

**Issue by venusgorilla** [alliedvision/VimbaPython#80]
Hi,
I couldn't find a function getting the AcquisitionFrameRateLimit which comes in relation with the exposure time. I only found it with the Vimba viewer. Do you have any suggestions?

Thanks.

**Comment by nordeh** [comment]
Hello,
assuming you solved the feature access for AcquisitionFrameRateLimit?
Otherwise please contact our support for further advice.
Thanks,
Norman
