### ISSUE TITLE
manual exposure time

### ISSUE THREAD

**Issue by clemensgaahs** [alliedvision/VimbaPython#81]
I'm trying to capture a spectrum with an AVT Manta camera. For that, I would need to set the exposure time to a fixed value. I only found `cam.ExposureAuto.set('Continous')` in the asynchronous_grab_opencv example. In #34 a user commented that there would be `cam.ExposureTime.set()` but I received an error that this method doesn't exist even if I used it in the position of the `ExposureAuto.set()` method in the example.

**Comment by arunprakash-avt** [comment]
cam.ExposureAuto.set('Continous') is the code to set the Exposure mode to Auto.
For manual setting the Exposure Time, check if the exposure mode auto is set to "Off". Then use the below code 
cam.ExposureTimeAbs.set(15000).

**Comment by clemensgaahs** [comment]
I've checked the exposure mode via the Vimba Viewer, and it worked with the code.

**Comment by smitshah-19** [comment]
> cam.ExposureAuto.set('Continous') is the code to set the Exposure mode to Auto. For manual setting the Exposure Time, check if the exposure mode auto is set to "Off". Then use the below code cam.ExposureTimeAbs.set(15000).

I want to set the White Balance, Gain and FPS of the video stream usingn VIMBA. But I have checked the module and I could not find any function/method to set any of this feature. Can you please help me out?
