### ISSUE TITLE
Sync Camera epoch time with PC time

### ISSUE THREAD

**Issue by ShankssD** [alliedvision/VimbaPython#82]
Hi,

I was just wondering if there was a way to sync the camera's epoch time with that from the PC (such as the value from time.time() in python). I would like to do this so that the timestamps I recieve from the camera are the current RealWorld time rather than time since boot of the camera. 

I have tried setting PTPMode to 'slave' and then setting the PTPAcquisitionGateTime but I do not think this is correct. 
Any help appreciated !!

Thanks

**Comment by arunprakash-avt** [comment]
Hi,

Thanks you for your email for PTP please check the following application note.
https://cdn.alliedvision.com/fileadmin/content/documents/products/cameras/various/appnote/GigE/PTP_IEEE1588_with_Prosilica_GT_GC_Manta.pdf
If you need further support , I request you to write to support@alliedvision.com.

**Comment by ShankssD** [comment]
Thank you for your help! Much appreciated

**Comment by Dongzhou-1996** [comment]
Hi! Have this problem been solved? I also found the timestamp provided by `Frame.get_timestamp()` is not in Unix timestamp format, how can I transform it by using PTP?


> Thank you for your help! Much appreciated
