### ISSUE TITLE
VimbaPython Installation

### ISSUE THREAD

**Issue by daniela-angulo** [alliedvision/VimbaPython#84]
Hi, 
I tried installing VimbaPython under Manjaro using the .sh file provided in the debug mode and I get the error "Error: No compatible Python version with pip support found. Abort." But I know I have python 3.9 and pip 21.1.2 installed. The search PATH is also the correct one. This is obviously a particular issue of my installation but I'd appreciate any help. 
Thanks.

**Comment by NiklasKroeger-AlliedVision** [comment]
You could try running the `Install.sh` script again with the flag `-d` (debug). This should give you a little more information on why some versions of Python might have been excluded.

Alternatively if you are comfortable using it you can use pip directly to install VimbaPython. `Install.sh` is only a small helper, that detects Python installations and suggests them before running the appropriate `pip` command. The script does not install any other components.

**Comment by daniela-angulo** [comment]
yeah, thank you! I just installed it with pip as you said and it worked
