### ISSUE TITLE
Where does the VimbaPython/Examples/synchronous_grab.py  write the frame?

### ISSUE THREAD

**Issue by lincolnelectric** [alliedvision/VimbaPython#88]
hello, I want to know that Where does the VimbaPython/Examples/synchronous_grab.py  write the frame? I can't find them any space.

**Comment by nordeh** [comment]
synchronous_grab.py grabs a frame or 10. To write to disc please add something like cv2. imwrite().

**Comment by lincolnelectric** [comment]
Thanks for your answer! 
You mean that I can add cv2. imwrite(frame) directly before the `print('Got {}'.format(frame), flush=True)` ?

Like that
`for frame in cam.get_frame_generator(limit=10, timeout_ms=3000):
                cv2. imwrite(frame)
                print('Got {}'.format(frame), flush=True)`

**Comment by nordeh** [comment]
more precisely:
for frame in cam.get_frame_generator(limit=10, timeout_ms=3000):
  image = frame.as_opencv_image()
  cv2.imwrite(frame.get_id() + '.png', image)

**Comment by lincolnelectric** [comment]
Thank you very much! My problem has been solved perfect！
but it just a little modification:
` for frame in cam.get_frame_generator(limit=10, timeout_ms=3000):`
                `image = frame.as_opencv_image()`
                `cv2.imwrite(str(frame.get_id()) + '.png', image)`

**Comment by nordeh** [comment]
very good.
Thank you,
Norman
