### ISSUE TITLE
Switch from hardware triggerMode to no triggermode

### ISSUE THREAD

**Issue by julienGautier77** [alliedvision/VimbaPython#89]
Hi
Thanks to develop this python library

I have some problem when I use trriggermode. 
I try to explain :
I use the camera with a hardware trigger and it's working fine.
But sometime I need to come back in triggermode "off" without sending any hardward trigger
In this case i have the following message : 
 VimbaFeatureError: Invalid access while calling 'set()' of Feature 'TriggerMode'. Read access: allowed. Write access: not allowed.

I need to disconnect the camera to use it again

I'm working with alvium camera or guppy Pro on windows 10 and last version of vimba 
I have tried acquisition  in synchronous mode and asynchronous mode 

Thanks in advance

**Comment by BernardoLuck** [comment]
Hello Julien, 

here is Bernardo from Allied Vision. I think it is better to analyze this issue internally. Please, let us continue this discussion using our Support ticket system: https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/
There we can prepare a Remote Session to help you further.

Best regards, 

Bernardo Luck Villanueva // Applications Engineer

**Comment by julienGautier77** [comment]
Thanks 
I have finally found a solution with a try /except method in a while loop and by reducing the timeout in the get_frame method : 
 while topRunAcq is not True :

with vmb:
            with self.parent.cam0:
               
                while self.stopRunAcq is not True :
                    
                
                    try: 
                        frame=self.parent.cam0.get_frame(timeout_ms=3000)
                        data=(frame.as_numpy_ndarray())
                        data=data[:,:,0]
                        data=np.rot90(data,3)
                
                        if str(frame.get_status()) == "FrameStatus.Complete" : #np.max(data)>0 or 
                
                            self.newDataRun.emit(data)

                    except:
                        pass
