### ISSUE TITLE
how about multi cameras synchronize catpure images?

### ISSUE THREAD

**Issue by tianyu06030020** [alliedvision/VimbaPython#93]
I have 2 same style cameras, how can trigger them on the same time and get the synchronized images?
I'm studying 3d-reconstruction, so need higher precision synchronized images. thanks a lot.

**Comment by arunprakash-avt** [comment]
Hello thanks for writing to us, for camera support can you please write us an email to support@alliedvision.com.

**Comment by tianyu06030020** [comment]
> Hello thanks for writing to us, for camera support can you please write us an email to [support@alliedvision.com](mailto:support@alliedvision.com).

thanks for your reply,  I have read trigger manual detailed and relative example program, I will send email for more help soon.
